Update sb-133.yml

diff --git a/.github/workflows/sb-133.yml b/.github/workflows/sb-133.yml
--- a/.github/workflows/sb-133.yml
+++ b/.github/workflows/sb-133.yml
@@ -1,58 +1,54 @@
 # This is a basic workflow to help you get started with Actions
-
 name: CI
+
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
   pull_request:
     branches: rc-merge
-   # Jobs to be executed
+
+# Jobs to be executed
 jobs:
-    Create-package:
-        runs-on: ubuntu-latest        
-        if: ${{ github.actor != 'dependabot[bot]' }}
-        steps:
-            # Checkout the source code
-            - name: 'Checkout source code'
-              uses: actions/checkout@v2
-              
-            # Install Salesforce CLI
-            - name: 'Install Salesforce CLI'
-              run: |
-                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
-                  mkdir ~/sfdx
-                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
-                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
-                  ~/sfdx/bin/sfdx version
-                  
-            # Store secret for dev hub
-            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
-              shell: bash
-              run: |
-                  echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
-                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
-                  if [ $secretFileSize == 1 ]; then
-                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
-                      exit 1;
-                  fi
-                  
-            # Authenticate dev hub
-            - name: 'Authenticate Dev Hub'
-              run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+  Create-package:
+    runs-on: ubuntu-latest
+    if: ${{ github.actor != 'dependabot[bot]' }}
+    steps:
+      # Checkout the source code
+      - name: 'Checkout source code'
+        uses: actions/checkout@v2
 
-            
-			      # Create Package
-			      - name: 'RC Package Create'
-			        run: sfdx force:package:version:create -p "Build RC" -w 10 -x -c -v rakesh.salesbolt@metacube.com 
-			  
-		      	# Create scratch org
-            - name: 'Create scratch org'
-              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
-			  
-			      # Install package on scratch org
-            - name: 'Install package on scratch org'
-              run: sf package install --package "Build RC" 
+      # Install Salesforce CLI
+      - name: 'Install Salesforce CLI'
+        run: |
+          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+          mkdir ~/sfdx
+          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+          ~/sfdx/bin/sfdx version
 
-            
-           
-            
+      # Store secret for dev hub
+      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+        shell: bash
+        run: |
+          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
+          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+          if [ $secretFileSize == 1 ]; then
+            echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+            exit 1;
+          fi
+
+      # Authenticate dev hub
+      - name: 'Authenticate Dev Hub'
+        run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+
+      # Create Package
+      - name: 'RC Package Create'
+        run: sfdx force:package:version:create -p "Build RC" -w 10 -x -c -v rakesh.salesbolt@metacube.com
+
+      # Create scratch org
+      - name: 'Create scratch org'
+        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
+
+      # Install package on scratch org
+      - name: 'Install package on scratch org'
+        run: sf package install --package "Build RC"
